---
title: "A4Q3 Presentation"
author: "Fenglin Chen"
date: "07/12/2021"
output: beamer_presentation
fontsize: 8pt
---

## Table of Contents

- Proportion of Changes
- Total Change
- Scatterplot of Changes
- Hypothesis / Significance Tests
- Results of Random Shuffling

## Proportion of Changes

```{r, echo=FALSE}
dropInvalid <- function(pop, column) {
  pop <- pop[!is.na(pop[,column]),]
  pop <- pop[!pop[,column] == -9,]
  pop <- pop[!pop[,column] == -99,]
}
popSize <- function(pop) {nrow(as.data.frame(pop))}

covid <- read.csv("WBCOVID_data.csv", header=TRUE)
covid <- dropInvalid(covid, "COVb2a")
countries <- unique(covid$Country)
countries2 <- c(countries[1:6], "Russia")
```

```{r, echo=FALSE}
library(knitr)
changes <- function(country){
  select <- covid[covid$Country == country,]
  N <- popSize(select)
  inc <- dropInvalid(select[select$COVb2a == 1,], "COVb2b")
  same <- select[select$COVb2a == 2,]
  dec <- dropInvalid(select[select$COVb2a == 3,], "COVb2c")
  c(popSize(inc)/N*100, popSize(same)/N*100, popSize(dec)/N*100,
    sum(inc[,"COVb2b"]), sum(dec[,"COVb2c"]))
}
all.res <- round(sapply(countries, FUN=changes), 3)
rownames(all.res) <- c("% Increase", "% Same", "% Decrease", 
                       "Total Increase", "Total Decrease")
colnames(all.res) <- countries2
amount.res <- all.res[1:3,]
kable(amount.res)
```

## Total Change

```{r, echo=FALSE}
percent.res <- all.res[4:5,]
kable(percent.res)
```

## Scatterplot of Changes (Increases)

```{r, echo=FALSE}
covid$Country2 <- match(covid$Country, countries)
covid.inc <- dropInvalid(covid, "COVb2b")
covid.dec <- dropInvalid(covid, "COVb2c")

plot(jitter(covid.inc$Country2, 0.75), covid.inc$COVb2b, xaxt = "n",
     pch=19, col=adjustcolor(3, 0.4), xlab="", ylab="% Increase",
     main="Percent Changes by Country")
axis(1, at=1:7, labels=countries2, las=2)
```

## Scatterplot of Changes (Decreases)

```{r, echo=FALSE}
plot(jitter(covid.dec$Country2, 0.75), -covid.dec$COVb2c, xaxt = "n", 
     yaxt = "n", pch=19, col=adjustcolor(2, 0.4), xlab="", ylab="% Decrease")
axis(1, at=1:7, labels=countries2, las=2)
axis(2, at=seq(from=-100,to=0,by=20), labels=seq(from=-100,to=0,by=20))
```

```{r, echo=FALSE}
mixRandomly <- function(pop) {
  pop1 <- pop$pop1
  n_pop1 <- nrow(pop1)
  pop2 <- pop$pop2
  n_pop2 <- nrow(pop2)
  mix <- rbind(pop1,pop2)
  select4pop1 <- sample(1:(n_pop1 + n_pop2), n_pop1, replace = FALSE)
  new_pop1 <- mix[select4pop1,]  
  new_pop2 <- mix[-select4pop1,]
  list(pop1=new_pop1, pop2=new_pop2)
}

getDiscrepancy <- function(variate) {
  function(pop, mode=1) {
    newpop1 <- dropInvalid(pop$pop1, variate)
    newpop2 <- dropInvalid(pop$pop2, variate)
    if (mode == 1){
      popSize(newpop1) - popSize(newpop2)
    } else {
      sum(newpop2[,variate]) - sum(newpop1[,variate])
    }
  }
}

compareCountries <- function(country1, country2, mode=1, discrepancy="COVb2c"){
  pop <- list(pop1 = subset(covid, covid$Country == country1), 
              pop2 = subset(covid, covid$Country == country2))
  set.seed(341)
  
  discFn <- getDiscrepancy(discrepancy)
  disc.random <- sapply(1:1000, FUN = function(...){ 
    discFn(mixRandomly(pop), mode) 
  })
  baseline <- discFn(pop, mode) - mean(disc.random)
  disc.random <- disc.random - mean(disc.random)
  mean( abs(disc.random) >= abs(baseline) )
}
```

## Significance Tests

```{r, echo=FALSE}
pop1 <- list(pop1 = subset(covid, covid$Country == "Hungary"), 
             pop2 = subset(covid, covid$Country == "Greece"))
discFn.c <- getDiscrepancy("COVb2c")

set.seed(341)
pop.pairs1 <- sapply(1:5000, FUN = function(...) {
  tmixpop <- mixRandomly(pop1)
  discFn.c(tmixpop)
})
res1 <- compareCountries("Hungary", "Greece", 1, "COVb2c")
```

```{r, echo=FALSE}
pop2 <- list(pop1 = subset(covid, covid$Country == "Italy"), 
             pop2 = subset(covid, covid$Country == "Poland"))
discFn.b <- getDiscrepancy("COVb2b")

set.seed(341)
pop.pairs2 <- sapply(1:5000, FUN = function(...) {
  tmixpop <- mixRandomly(pop2)
  discFn.b(tmixpop)
})
res2 <- compareCountries("Italy", "Poland", 1, "COVb2b")
```

```{r, echo=FALSE}
pop3 <- list(pop1 = subset(covid, covid$Country == "Bulgaria"), 
             pop2 = subset(covid, covid$Country == "Romania"))

set.seed(341)
pop.pairs3 <- sapply(1:5000, FUN = function(...) {
  tmixpop <- mixRandomly(pop3)
  discFn.b(tmixpop, mode=2)
})
res3 <- compareCountries("Bulgaria", "Romania", 2, "COVb2b")
```

```{r, echo=FALSE}
p.vals <- rbind(c("Hungary vs. Greece", "Italy vs. Poland", "Bulgaria vs. Romania"),
                c(res1, res2, res3))
rownames(p.vals) <- c("Pair", "p-value")
kable(p.vals)
```

## Results of Random Shuffling

```{r, echo=FALSE}
par(mfrow=c(1,3), mar=c(2.5, 2.5, 1.5, 0), oma=c(2, 2, 0, 0))
hist(pop.pairs1, breaks = 20, main = "Hungary / Greece", xlim=c(-60, 120), 
     xlab = "Difference in Bad Proportions", col = "lightgrey")
abline(v = discFn.c(pop1), col = "red", lwd = 2)

hist(pop.pairs2, breaks = 20, main = "Italy / Poland", xlim=c(-80, 0), 
     xlab = "Difference in Good Proportions", col = "lightgrey")
abline(v = discFn.b(pop2), col = "red", lwd = 2)

hist(pop.pairs3, breaks = 20, main = "Bulgaria / Romania",
     xlab = "Difference in Total Change", col = "lightgrey")
abline(v = discFn.b(pop3, 2), col = "red", lwd = 2)
```